id: IBD70DCB6
legacy_id: P004463
ocr_import_info:
  bdrc_scan_id: W1KG4475
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T15:24:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:42:54.083397+00:00'
last_modified: 2022-09-01 00:42:58.516425
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4475
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4475
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་རྣམ་པར་ཐར་པ་ལ་བསྟོད་པ་བདུད་དཔུང་ཕྱེ་མར་འཐག་པ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7276036558477751
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG4506:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4506
      total_pages: 42
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4506.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7276036558477751
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
