id: IBD70DCB6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:25:10+00:00'
last_modified: '2022-06-08T01:15:53.421847+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4475
  title: 'བཅོམ་ལྡན་འདས་ཐུབ་པའི་དབང་པོའི་རྣམ་པར་ཐར་པ་ལ་བསྟོད་པ་བདུད་དཔུང་ཕྱེ་མར་འཐག་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6325':
      image_group_id: I1KG4506
      title: ''
      total_pages: 42
      order: 1
      base_file: 6325.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
